apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true


      containers:
        - name: sales
          resources:
            requests:
              cpu: "500m"
              memory: "500m"
            limits:
              cpu: "100m"
              memory: "100m"

